app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('csoAdmin2yKz3/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('articles/', include('blog.urls', namespace='blog')),
    path('tariffs/', include('tariffs.urls', namespace='tariffs')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from blog.views import BlogView, ArticleView

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='index'),
    path('article/<slug:slug>/', ArticleView.as_view(), name='article'),
]

main/urls.py
from django.urls import path
from main.views import Error404, Error500, IndexView, AboutView, ContactsView

app_name = 'main'

handler404 = Error404.as_view()
handler500 = Error500.as_view()

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
]

tariffs/urls.py
from django.urls import path
from tariffs.views import TariffsView, BusinessView

app_name = 'tariffs'

urlpatterns = [
    path('', TariffsView.as_view(), name='index'),
    path('business/', BusinessView.as_view(), name='business'),
]

main/models.py
from django.db import models

class Main(models.Model):
    title = models.CharField(max_length=200, unique=True, null=True, verbose_name='Заголовок')
    sub_title = models.CharField(max_length=200, unique=True, null=True, verbose_name='Підзаголовок')
    text = models.TextField( null=True, verbose_name='Текст')


    class Meta:
        db_table = 'main'
        verbose_name = 'Головні статті'
        verbose_name_plural = 'Головні статті'

    def __str__(self):
        return self.title
    
class FAQ(models.Model):
    title = models.CharField(max_length=200, unique=True, null=True, verbose_name='Заголовок')
    text = models.TextField(unique=True, null=True, verbose_name='Текст')


    class Meta:
        db_table = 'faq'
        verbose_name = 'Часті питання'
        verbose_name_plural = 'Часті питання'

    def __str__(self):
        return self.title
    
class Vacancy(models.Model):
    title = models.CharField(max_length=255, null=True, verbose_name="Посада")
    responsibilities = models.TextField(null=True, verbose_name="Обов'язки")
    requirements = models.TextField(null=True, verbose_name="Вимоги")
    conditions = models.TextField(null=True, verbose_name="Умови роботи")
  
    class Meta:
        db_table = 'vacancy'
        verbose_name = 'Вакансію'
        verbose_name_plural = 'Вакансії'

    def get_responsibilities_list(self):
        return self.responsibilities.split(';')

    def get_requirements_list(self):
        return self.requirements.split(';')

    def get_conditions_list(self):
        return self.conditions.split(';')


    def __str__(self):
        return self.title
    

main/forms.py
from django import forms


class OrderForm(forms.ModelForm):
    firstname = forms.CharField(label="Ім'я", max_length=100, required=True)
    lastname = forms.CharField(label="Прізвище", max_length=100, required=True)
    surname = forms.CharField(label="По-батькові", max_length=100, required=False)
    adress = forms.CharField(label="Адреса", required=False)
    street = forms.CharField(required=False)
    building = forms.CharField(required=False)
    phone = forms.CharField(label="Контактний телефон", max_length=12, required=True)
    comment = forms.CharField(label="Коментар", required=False)

main/views.py
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from blog.models import Articles
from main.models import FAQ, Vacancy
from tariffs.models import Tariffs

@method_decorator(cache_page(60 * 30), name='dispatch')
class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Головна сторінка'
        context['latest_articles'] = Articles.objects.all().order_by('-date')[:4]
        context['slider_articles'] = Articles.objects.filter(category__name='Акція').order_by('-date')[:5]
        context['tariffs'] = Tariffs.objects.all().order_by('?')[:3]
        context['faqs'] = FAQ.objects.all()
        return context


@method_decorator(cache_page(60 * 60 * 24), name='dispatch')
class AboutView(TemplateView):
    template_name = 'main/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Про нас'
        return context

@method_decorator(cache_page(60 * 60), name='dispatch')
class ContactsView(TemplateView):
    template_name = 'main/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.all()
        context['title'] = 'Контакти та вакансії'
        return context
    
class Error404(TemplateView):
    template_name = '404.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сторінка не знайдена'
        return context

class Error500(TemplateView):
    template_name = '404.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Помилка сервера'
        return context

main/templates/main/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
		<main class="page">
			<section data-watch class="about">
				<h1 class="about__title title title--large">Про компанію</h1>
				<div class="about__container">
					<h2 class="about__title title">Торшки історії</h2>
					<div class="about__content">
						<div class="about__text-block">
							<div class="about__text text">
								<p>ЦСО (Центр Сервісного Обслуговування) був заснований у 2005 році групою ентузіастів у сфері
									телекомунікацій. Ініціатори створення компанії мали на меті забезпечити високоякісний доступ
									до Інтернету для мешканців невеликих міст та селищ.</p>
								<p>Спочатку ЦСО обслуговував лише кілька десятків клієнтів, але завдяки високому рівню
									обслуговування та надійності мережі, компанія швидко здобула популярність. У 2008 році компанія
									впровадила новітні технології оптоволоконного зв'язку, що дозволило значно розширити зону
									покриття та збільшити швидкість інтернету. Протягом наступних років ЦСО відкрив декілька філій
									у різних регіонах, продовжуючи інвестувати у розвиток інфраструктури.</p>
								<p>Завдяки своєму інноваційному підходу та
									орієнтації на клієнта, компанія отримала численні нагороди у галузі телекомунікацій. Сьогодні
									ЦСО обслуговує понад 100,000 клієнтів, надаючи надійний та швидкий доступ до Інтернету.</p>
							</div>
						</div>
						<img class="about__image ibg" src="{% static "img/about/01.webp" %}" alt="Image">
					</div>
					<h2 class="about__title title">Чому ЦСО</h2>
					<div class="about__content about__content--reverse">
						<div class="about__text-block">
							<div class="about__text text">
								<p>Обравши ЦСО (Центр Сервісного Обслуговування) як свого інтернет-провайдера,
									ви отримуєте ряд переваг.</p>
							</div>
							<h3 class="about__sub-title sub-title">Високоякісний сервіс</h3>
							<div class="about__text text">
								<p>ЦСО відомий своєю стабільною та надійною мережею, що забезпечує безперебійний доступ до Інтернету навіть у віддалених районах.</p>
							</div>
							<h3 class="about__sub-title sub-title">Швидкість та продуктивність</h3>
							<div class="about__text text">
								<p>Завдяки використанню новітніх технологій оптоволоконного зв'язку, ЦСО пропонує високі що ідеально підходить для стрімінгу, онлайн-ігор та дистанційної роботи.</p>
							</div>
							<h3 class="about__sub-title sub-title">Клієнтоорієнтованість</h3>
							<div class="about__text text">
								<p>Компанія завжди ставить на перше місце потреби своїх клієнтів, пропонуючи швидку та ефективну технічну підтримку 24/7. Спеціалісти завжди готові допомогти у вирішенні будь-яких питань.</p>
							</div>
							<h3 class="about__sub-title sub-title">Гнучкі тарифи</h3>
							<div class="about__text text">
								<p>ЦСО пропонує різноманітні тарифні плани, що дозволяють кожному клієнту обрати оптимальний варіант за ціною та швидкістю, враховуючи індивідуальні потреби.</p>
							</div>
						</div>
						<img class="about__image ibg" src="{% static "img/about/02.webp" %}" alt="Image">
					</div>
					<div class="about__content">
						<div class="about__text-block">
							<h3 class="about__sub-title sub-title">Інновації та розвиток</h3>
							<div class="about__text text">
								<p>Компанія постійно впроваджує нові технології та вдосконалює свою інфраструктуру,
									щоб забезпечити клієнтів найкращими умовами для роботи та розваг в Інтернеті.</p>
							</div>
							<h3 class="about__sub-title sub-title">Високий рівень задоволеності клієнтів</h3>
							<div class="about__text text">
								<p>Більшість клієнтів ЦСО задоволені наданими послугами, що підтверджується
									численними позитивними відгуками та високими оцінками.</p>
							</div>
							<h3 class="about__sub-title sub-title">Нагороди та визнання</h3>
							<div class="about__text text">
								<p>ЦСО отримав численні нагороди у галузі телекомунікацій, що є свідченням
									високого рівня професіоналізму та якості послуг, які надає компанія.</p>
							</div>
						</div>
						<img class="about__image ibg" src="{% static "img/about/03.webp" %}" alt="Image">
					</div>
				</div>
			</section>
		</main>
{% endblock %}

main/templates/main/contacts.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="page">
  <section data-watch class="contacts">
    <div class="contacts__container">
      <div class="contacts__title-block title-block">
        <h2 class="title-block__title title">Контакти</h2>
        <div class="title-block__text text">
          Наш інтернет-провайдер надає послуги цілодобово, без вихідних та
          святкових днів. Ми завжди готові забезпечити вам стабільний та швидкий
          доступ до мережі Інтернет
        </div>
      </div>
      <div class="contacts__body">
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Офіс у центрі міста</h4>
          <ul class="contacts__items">
            <li class="contacts__item _icon-location">
              м. Золочів, вул. С.Бандери, 11
            </li>
            <li class="contacts__item _icon-clock">
              Пн-Пт: 9:00 - 18:00, <span>Сб: 9:00 - 14:00</span>
            </li>
            <li class="contacts__item">
              <a class="contacts__link _icon-phone" href="tel:0673703236"
                >+38 (067) 370 32 36</a
              >
            </li>
            <li class="contacts__item">
              <a class="contacts__link _icon-mail" href="mailto:cso@gmail.com"
                >cso@gmail.com</a
              >
            </li>
          </ul>
        </div>
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Головний офіс</h4>
          <ul class="contacts__items">
            <li class="contacts__item _icon-location">
              м. Золочів, вул. Тернопільська, 3
            </li>
            <li class="contacts__item _icon-clock">Пн-Пт: 9:00 - 18:00</li>
            <li class="contacts__item">
              <a class="contacts__link _icon-phone" href="tel:0673703236"
                >+38 (067) 370 32 36</a
              >
            </li>
            <li class="contacts__item">
              <a class="contacts__link _icon-mail" href="mailto:cso@gmail.com"
                >cso@gmail.com</a
              >
            </li>
          </ul>
        </div>
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Технічна підтримка</h4>
          <ul class="contacts__items">
            <li class="contacts__item _icon-clock">9:00 - 20:00</li>
            <li class="contacts__item">
              <a class="contacts__link _icon-phone" href="tel:0673703236"
                >+38 (067) 370 32 36</a
              >
            </li>
            <li class="contacts__item">
              <a class="contacts__link _icon-mail" href="mailto:cso@gmail.com"
                >cso@gmail.com</a
              >
            </li>
          </ul>
        </div>
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Чат підтримки</h4>
          <div class="contacts__text text">
            Ми також пропонуємо підтримку через онлайн-чат на нашому сайті. Наші
            фахівці з радістю допоможуть вам з будь-якими питаннями або
            проблемами.
          </div>
          <ul class="contacts__items">
            <li class="contacts__item">
              <a
                class="contacts__link _icon-telegram"
                target="_blank"
                href="https://web.telegram.org/"
                >Цілодобово</a
              >
            </li>
          </ul>
        </div>
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Соціальні мережі</h4>
          <div class="contacts__text text">
            Слідкуйте за нашими новинами та акціями у соціальних мережах:
          </div>
          <ul class="contacts__items">
            <li class="contacts__item">
              <a
                class="contacts__link _icon-facebook"
                target="_blank"
                href="https://www.facebook.com/cso.zolochiv"
                >Facebook</a
              >
            </li>
            <li class="contacts__item">
              <a
                class="contacts__link _icon-instagram"
                target="_blank"
                href="https://www.instagram.com/"
                >Instagram</a
              >
            </li>
            <li class="contacts__item">
              <a
                class="contacts__link _icon-telegram"
                target="_blank"
                href="https://web.telegram.org/"
                >Telegram спільнота</a
              >
            </li>
          </ul>
        </div>
        <div class="contacts__content">
          <h4 class="contacts__sub-title sub-title">Важлива інформація</h4>
          <div class="contacts__text text">
            <p>
              Наші офіси обладнані всім необхідним для комфортного
              обслуговування клієнтів. Якщо вам потрібна допомога у налаштуванні
              обладнання або консультація, наші спеціалісти завжди готові вам
              допомогти.
            </p>
            <p>Дякуємо, що обираєте нас!</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section data-watch class="vacancies">
    <div class="vacancies__container">
      <div class="vacancies__title-block title-block">
        <h2 class="title-block__title title">Вакансії</h2>
        <div class="title-block__text text">
          Ми завжди шукаємо талановитих та амбітних людей, які хочуть
          приєднатися до нашої команди. Якщо ви прагнете розвиватися у сфері
          телекомунікацій, працювати у дружньому колективі та робити світ кращим
          через надання високоякісних послуг Інтернету, ми запрошуємо вас
          розглянути наші актуальні вакансії.
        </div>
      </div>
      <div class="vacancies__body">
        {% if vacancies %} {% for vacancy in vacancies %}
        <div class="vacancies__content">
          <h4 class="vacancies__sub-title sub-title">{{ vacancy.title }}</h4>
          <ul class="vacancies__items">
            <li class="vacancies__item vacancies__item--title">Обов'язки:</li>
            {% for responsibility in vacancy.get_responsibilities_list %}
            <li class="vacancies__item">{{ responsibility }}</li>
            {% endfor %}
          </ul>
          <ul class="vacancies__items">
            <li class="vacancies__item vacancies__item--title">Вимоги:</li>
            {% for requirement in vacancy.get_requirements_list %}
            <li class="vacancies__item">{{ requirement }}</li>
            {% endfor %}
          </ul>
          <ul class="vacancies__items">
            <li class="vacancies__item vacancies__item--title">
              Умови роботи:
            </li>
            {% for condition in vacancy.get_conditions_list %}
            <li class="vacancies__item">{{ condition }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endfor %} {% else %}
        <p>Немає доступних вакансій.</p>
        {% endif %}
        <div class="vacancies__content vacancies__content--last">
          <h4 class="vacancies__sub-title sub-title">Як подати заявку</h4>
          <div class="vacancies__sub-text text">
            Щоб стати частиною нашої команди, надішліть своє резюме та
            супровідний лист на електронну адресу cso@gmail.com із зазначенням
            назви вакансії у темі листа. Ми ретельно розглянемо вашу кандидатуру
            та зв'яжемося з вами для подальшого обговорення.
          </div>
          <ul class="vacancies__items">
            <li class="vacancies__item vacancies__item--title">
              Чому обирають нас?
            </li>
            <li class="vacancies__item">
              <span>Професійний розвиток:</span> Ми підтримуємо прагнення наших
              співробітників до професійного зростання та надаємо можливості для
              навчання.
            </li>
            <li class="vacancies__item">
              <span>Дружній колектив:</span> У нас працюють доброзичливі та
              відкриті люди, готові допомагати один одному.
            </li>
            <li class="vacancies__item">
              <span>Стабільність:</span> Ми пропонуємо офіційне працевлаштування
              та стабільну заробітну плату.
            </li>
            <li class="vacancies__item">
              <span>Комфортні умови:</span> Сучасні офіси, зручне робоче місце
              та приємна атмосфера.
            </li>
          </ul>
          <div class="vacancies__sub-text text">
            Приєднуйтесь до нашої команди та зробіть свій внесок у розвиток
            передових технологій разом з нами!
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="page">
    <section data-watch class="hero">
        <div class="hero__container">
            <div class="hero__body">
                <div class="hero__slider swiper">
                    <div class="hero__wrapper swiper-wrapper">
                        {% for article in slider_articles %}
						<div class="hero__slide swiper-slide">
							<div class="hero__content">
								<h1 data-swiper-parallax="-300" class="hero__title title title--hero"><a href="{% url "blog:article" article.slug %}">{{article.title}}</a></h1>
								<a data-swiper-parallax="-500" href="{% url "blog:article" article.slug %}" class="hero__button button">Детально</a>
							</div>
							<img class="hero__image ibg" src="{{article.image.url}}" alt="{{article.title}}">
						</div>
						{% endfor %}
                    </div>
                </div>
                <div class="hero__arrows">
                    <div class="hero__arrow hero__arrow--prev _icon-chevron"></div>
                    <div class="hero__arrow hero__arrow--next _icon-chevron"></div>
                </div>
                <div class="hero__bullets"></div>
            </div>
        </div>
    </section>
    <section data-watch class="services">
        <div class="services__container">
            <h2 class="services__title title">Послуги</h2>
            <div class="services__items">
                <div class="services__item item-services">
                    <a href="{% url "tariffs:index" %}" class="item-services__icon">
                        <img src="{% static "img/services/01.svg" %}" alt="Інтернет">
                    </a>
                    <h5 class="item-services__title title title--item"><a href="{% url "tariffs:index" %}">Інтернет</a></h5>
                    <div class="item-services__text text">Безкоштовне підключення до мережі Інтернет</div>
                </div>
                <div class="services__item item-services">
                    <a href="{% url "tariffs:business" %}" class="item-services__icon">
                        <img src="{% static "img/services/02.svg" %}" alt="Для бізнесу">
                    </a>
                    <h5 class="item-services__title title title--item"><a href="{% url "tariffs:business" %}">Для бізнесу</a></h5>
                    <div class="item-services__text text">Ваш бізнес на високій швидкості</div>
                </div>
                <div class="services__item item-services">
                    <a href="https://www.facebook.com/csosolar?paipv=0&eav=AfZqSSgGzZqXzTg3jc7uO36UBM1j3OUlcchgdJuQo98DVaFNFabHan8KBlZzOX2RYW4&_rdr" class="item-services__icon">
                        <img src="{% static "img/services/03.svg" %}" alt="CSOSolar">
                    </a>
                    <h5 class="item-services__title title title--item"><a href="https://www.facebook.com/csosolar?paipv=0&eav=AfZqSSgGzZqXzTg3jc7uO36UBM1j3OUlcchgdJuQo98DVaFNFabHan8KBlZzOX2RYW4&_rdr">Сонячна енергія</a></h5>
                    <div class="item-services__text text">Встановлення сонячних станцій</div>
                </div>
                <div class="services__item item-services">
                    <a href="{% url "payment:index" %}" class="item-services__icon">
                        <img src="{% static "img/services/04.svg" %}" alt="Icon">
                    </a>
                    <h5 class="item-services__title title title--item"><a href="{% url "payment:index" %}">Оплата</a></h5>
                    <div class="item-services__text text">Онлайн оплата послуг</div>
                </div>
            </div>
        </div>
    </section>
    <section data-watch class="tariffs">
        <div class="tariffs__container">
            <h2 class="tariffs__title title">Тарифи</h2>
            <div class="tariffs__cards">
            {% for tariff in tariffs %}
            <div class="tariffs-page__card card-tariff">
            <div class="card-tariff__title title title--item">
              {{ tariff.title }}
            </div>
            <div class="card-tariff__price">{{ tariff.price }} грн</div>
            <div class="card-tariff__speed">{{ tariff.speed }}</div>
            <div class="card-tariff__type">{{ tariff.building_type }}</div>
            <div class="card-tariff__text text">{{ tariff.text }}</div>
            </div>
            {% endfor %}
            </div>
            <a href="{% url "tariffs:index" %}" class="tariffs__button button">Детально про тарифи</a>
        </div>
    </section>
    <section data-watch class="blog">
        <div class="blog__container">
            <h2 class="blog__title title">Новини та акції</h2>
            <div class="blog__items">
                {% for article in latest_articles %}
				<div class="blog__item item-blog">
					<div class="item-blog__label {% if article.category.name == "Акція" %} item-blog__label--accent{% endif %}">{{article.category}}</div>
					<a href="{% url "blog:article" article.slug %}" class="item-blog__link">
						<img class="item-blog__image ibg" src="{{article.image.url}}" alt="{{article.title}}">
					</a>
					<div class="item-blog__content">
						<div class="item-blog__date">{{article.date}}</div>
						<h5 class="item-blog__title title title--item"><a href="{% url "blog:article" article.slug %}">{{article.title}}</a></h5>
						<div class="item-blog__text text">{{article.text|truncatechars:170}}</div>
						<a href="{% url "blog:article" article.slug %}" class="item-blog__button button">Детально</a>
					</div>
				</div>
				{% endfor %}
            </div>
            <a href="{% url "blog:index" %}" class="blog__button button">Всі новини</a>
        </div>
    </section>
    <section data-watch class="faq">
        <div class="faq__container">
            <h2 class="faq__title title">Часті питання</h2>
            <div class="faq__body">
                <div data-spollers class="faq__spollers spollers">
                    {% for faq in faqs %}
						<details class="spollers__item">
							<summary class="spollers__title">{{faq.title}}</summary>
							<div class="spollers__body">
								<div class="spollers__text text">{{faq.text}}</div>
							</div>
						</details>
					{% endfor %}
                </div>
            </div>
        </div>
    </section>
    <section data-watch class="map">
        <div class="map__container">
            <h2 class="map__title title">Карта покриття</h2>
            <div class="map__body">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52722.57068696038!2d24.857460420369673!3d49.80923921740783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473007fcdf1dbefd%3A0x68d7724e21006816!2z0JfQvtC70L7Rh9GW0LIsINCb0YzQstGW0LLRgdGM0LrQsCDQvtCx0LvQsNGB0YLRjCwgODA3MDA!5e1!3m2!1suk!2sua!4v1720172668142!5m2!1suk!2sua" style="border:0;" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </section>
</main>
{% endblock %}